### ISSUE TITLE
V1.51 bspatch and copying maps errors

### ISSUE THREAD

**Issue by StenApp** [NightFright2k19/worldtour_raze#1]
Hi when i run your script, these errors on a german Windows 10 occur:

```
Falscher Parameter.
E5L8 patch applied. Backup saved as E5L8B.map.
```
and later
```
2022/10/23 19:49:28 FEHLER 123 (0x0000007B) Zugriff auf Zielverzeichnis C:\Users\Sten\Downloads\worldorder_raze\data\temp\maps\
Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
```
What can i do?

**Comment by NightFright2k19** [comment]
This info alone is not enough to figure out what might be going on. Helpful to know would be the following:

1) What exactly did you do before executing this script?
2) At which point of the installation exactly does this happen, i.e. during which steps? (First problem seems to occur during E5L8 copying, the other while copying maps? There are no problems with other steps, e.g. sounds or art files?)
3) Did you try with not choosing any of the optional changes, i.e. the duke3d.grp conversion and the E5L8 exchange?

A first idea:
You seem to have a "worldorder_raze" dir. Are you sure that's right? Normally you copy these files into your Raze dir, they cannot be copied into a new folder. Zip programs like to create new folders during extraction, but everything needs to be copied into the Raze dir as is. That means the batch file must be in the same folder as raze.exe.

**Comment by StenApp** [comment]
I moved my Duke Nukem 3D Twentieth Anniversary World Tour folder to the user/downloads folder.

i changed the line in the script to this:
set "src=%steam%\Duke Nukem 3D Twentieth Anniversary World Tour"
and removed all cls to see where it fails.
I modified the first line to:

@echo off & "%__APPDIR__%chcp.com" 65001 >nul

i unpacked the contents of worldorder_raze.zip to user/downloads/worldorder_raze and put in raze 1.5.0 files too.

Then i started the script by rightclicking with admin rights.
Steam folder set to „C:/users/user/downloads“ ( copied from Explorer)
Batch script folder acknowledged

I skipped duke3d.grp creation an chose to extend the level.

The i get an error at bspatch section and later one at the maps section.

**Comment by NightFright2k19** [comment]
It's not supposed to work like that. Editing the script is neither recommended nor supported. 

Have you tried just installing the game via Steam, then using auto detection by just pressing "Enter" and then entering your target directory?

I will attempt to replicate this tomorrow, anyway.

**Comment by StenApp** [comment]
No i didn‘t tried it yet with steam, i was so disappointed with this duke version. So i decided to quickly move it out of steam folder and get my worldorder.grp.

**Comment by NightFright2k19** [comment]
I have located and (hopefully) fixed the problem in the script. It was related to the E5L8 patch (could not copy the files since it did not find the required subdir). 

[Please download latest v1.52](https://github.com/NightFright2k19/worldorder_raze/releases/tag/v152) and follow the instructions precisely this time (keep WT installed until the script is finished).

**Comment by StenApp** [comment]
Thank you,
I will try it today evening

**Comment by StenApp** [comment]
Version 1.52 created a valid grp file without errors.
It used the steam folder.

Thanks for solving the problem!

**Comment by NightFright2k19** [comment]
Thanks for pointing out the issue. I am not sure how it could slip my attention, but better fixed late than never.
