### ISSUE TITLE
7z.dll needs to be packaged for PCs without 7zip installed.

### ISSUE THREAD

**Issue by Don-Dokken** [NightFright2k19/worldtour_raze#2]
Hello! first of all, the script worked wonders. Thanks a lot!

However, I ran into an issue first, basically 7z.exe was complaining it couldn't find 7z.dll. In my PC I use PeaZip, so obviously I don't have it. I then grabbed the latest 7zip installer from it's site and copied over 7z.exe (since its a newer version than the one bundled with the script) and 7z.dll to the script's data folder. After that, the script ran perfectly.

**Comment by NightFright2k19** [comment]
Resolved in version 1.53. Thanks for the report!
